### ISSUE TITLE
Que el player se frene al terminar o cancelar la grabación 

### ISSUE THREAD

**Issue by iglosiggio** [hugoruscitti/huayra-ritmos#14]
Se graba mientras se reproduce, por lo que varias combinaciones de "detener reproducción" y "detener grabación" son problemáticas.

**Comment by iglosiggio** [comment]
Otra opción posible es no permitir cancelar la grabación, suena raro pero intenté implementar lo primero y se me armaba un espaguetti horrible de código, voy a ver más adelante si se me ocurre alguna forma mejor.

**Comment by iglosiggio** [comment]
Estos errores están casi todos solucionados con 0bd6bfe10a281535c441f351421b890eba510fcf el único que quedaría buscar una forma elegante de reparar es que se cancele la grabación si el usuario decide frenar la reproducción del ritmo. 

De esto último existen dos casos:
- Se disparó 'pattern-end' en el servicio
- Aún no se disparó y la promise está flotando en un limbo

De todas formas es bastante usable

**Comment by hugoruscitti** [comment]
Relacionado por #22, lo cierro en favor del otro.
