### ISSUE TITLE
Deshabilitar el livereload al armar la versión que va al paquete

### ISSUE THREAD

**Issue by iglosiggio** [hugoruscitti/huayra-ritmos#15]
El livereload le pide al kernel que escuche eventos por un montón de archivos, cosa que no tiene sentido para las net. Además es sabido que el watch de node está medio bugueado.

**Comment by hugoruscitti** [comment]
Con la nueva versión, que usa electron, ¿no deberíamos tener este problema no'cierto?, ¿podríamos cerrarlo @iglosiggio ?

**Comment by iglosiggio** [comment]
Cierre don!

**Comment by hugoruscitti** [comment]
👏👏👏
