### ISSUE TITLE
paquete roto

### ISSUE THREAD

**Issue by ftoledo** [hugoruscitti/huayra-ritmos#16]
Seleccionando el paquete huayra-ritmos-data previamente no seleccionado.
(Leyendo la base de datos ... 425392 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../huayra-ritmos-data_0.9.0-5_all.deb ...
Desempaquetando huayra-ritmos-data (0.9.0-5) ...
dpkg: error al procesar el archivo /var/cache/apt/archives/huayra-ritmos-data_0.9.0-5_all.deb (--unpack):
 intentando sobreescribir `/usr/share/huayra-ritmos/dist/sounds/Alchemist/Alchemist Shaker 3.wav', que está también en el paquete huayra-ritmos 0.6.0-1
dpkg-deb: error: el subproceso copiado fue terminado por la señal (Tubería rota)
Preparando para desempaquetar .../huayra-ritmos_0.9.0-5_all.deb ...
Desempaquetando huayra-ritmos (0.9.0-5) sobre (0.6.0-1) ...
Procesando disparadores para hicolor-icon-theme (0.13-1) ...
Procesando disparadores para gnome-menus (3.13.3-6) ...
Procesando disparadores para bamfdaemon (0.2.118-1) ...
Rebuilding /usr/share/applications/bamf.index...
Procesando disparadores para mime-support (3.58) ...
Procesando disparadores para desktop-file-utils (0.22-1) ...
Se encontraron errores al procesar:
 /var/cache/apt/archives/huayra-ritmos-data_0.9.0-5_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
ftoledo@ftoledo-huayra:~$

**Comment by hugoruscitti** [comment]
Ahí subí la actualización con los cambios que me comentaste @ftoledo, debería estar resuelto en `huayra-ritmos_0.9.0-6`.
