### ISSUE TITLE
Comportamiento extraño al cerrar un modal pulsando en el fondo de pantalla.

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#18]
Cuando se intenta configurar una pista, por ejemplo para cambiar de color o cambiar el volúmen, no se puede cerrar el modal pulsando en el fondo oscuro del modal. Al pulsar el fondo oscuro desaparecen de pantalla el nombre del track y el resto de los valores.

**Comment by iglosiggio** [comment]
Al final era un error tontísimo de haber escrito mal el nombre de una acción
