### ISSUE TITLE
Agregar un mensaje cuando no hay pistas y deshabilitar botones

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#21]
Cuando se borran todas las pistas aún se puede pulsar play y record. Estaría mucho mejor que se deshabiliten esos controles y que también se muestre un mensaje que indique si no hay pistas.

**Comment by iglosiggio** [comment]
Tiene sentido esto? Dado el issue #23 creo que tiene mucho más sentido de cara al usuario no podes borrar la última pista (y que en todo caso él la cambie al sonido correspondiente)
