### ISSUE TITLE
Agregar una forma de cambiar el sonido de las pistas

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#23]
Actualmente se puede cambiar el volúmen y color de las pistas, pero no hay forma de cambiar el sample de audio. Sería útil que se pueda cambiar el sample de una pista ya creada.

**Comment by iglosiggio** [comment]
Ahí tenés una prueba concepto que, si bien funcional, rompe visualmente la aplicación :-1:
