### ISSUE TITLE
Hacer que el selector de color muestre el color actual

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#24]
El selector de colores del diálogo de pista no muestra el color actual, y cuando se selecciona un nuevo color no hay ninguna pista visual para darse cuenta de que el color cambió, ni cual es el color actualmente seleccionado.

**Comment by iglosiggio** [comment]
No se si es lo mejor visualmente (no soy el mejor en eso :-1:) pero ahora pusheo un fix
