### ISSUE TITLE
Portar la aplicación a electron

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#28]
Notamos que nwjs tiene unos bugs de audio que nos hacen pensar que pasar a electron pueden resolverlos.

**Comment by hugoruscitti** [comment]
Pude hacer que funcione sobre electron, pero tuve que actualizar a ember 2.6.2 y no llegué a implementar nada relacionado con la api de electron.

Creo que para una prueba inicial sobre webaudio nos puede servir @iglosiggio, si vemos que no se traba tanto como nwjs lo seguimos, y si no anda 🤗

**Comment by iglosiggio** [comment]
Genial huguín! Mañana en la oficina lo vemos y marcamos todo lo que entra
en la beta de Huayra.
Largá el laburo que ya es tarde jajaja 😂

**Comment by hugoruscitti** [comment]
Hicimos las pruebas con @iglosiggio y anduvo mucho mejor con electron, se ve que implementa webaudio un poco mejor que la versión de nwjs que veníamos usando. Dejo abierto el issue para cerrarlo cuando tengamos todo integrado a master.
