### ISSUE TITLE
Quitar el grabador de audio

### ISSUE THREAD

**Issue by iglosiggio** [hugoruscitti/huayra-ritmos#29]
Dada la situación actual de que la calidad de la grabación es subóptima estaría bueno ponerlo o bien como feature experimental (marcada que no funciona correctamente) o borrándolo y revirtiendo ese parche en una branch donde se desarrolle un grabador que tenga el funcionamiento deseado para versiones futuras.

En resumen: marcar qué estamos dispuestos a dejar en condición óptima para el deadline y no colgar con issues que, si bien geniales, podrían retrasar el release.

**Comment by hugoruscitti** [comment]
Sip, me parece lo mejor quitar la funcional directamente, pongámoslo como un feature a hacer en el futuro.

+1

**Comment by iglosiggio** [comment]
Mañana hago el borrado de eso y armo una branch donde revierto el commit!

**Comment by hugoruscitti** [comment]
Genia!

**Comment by ftoledo** [comment]
De última se puede usar la salida de monitor de pulse y se graba ese output con el audacity:

![pavucontrol_capturemonitor](https://cloud.githubusercontent.com/assets/95441/17553573/e561d268-5edc-11e6-8420-5c7f7c27c673.png)

**Comment by hugoruscitti** [comment]
Dejo un link al grabador deshabilitado, así en el futuro podemos retomarlo: https://github.com/HuayraLinux/huayra-ritmos/commit/19b21ddd75e2c09877f1a2b1c2f40ecbbfcd258c
