### ISSUE TITLE
Armar el paquete huayra-ritmos-data

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#38]
Diego armó el repositorio con los sonidos adicionales para huayra-ritmos, tendríamos
que agregar al repositorio pkg-huayra-ritmos una referencia a este repositorio
nuevo para generar el paquete huayra-ritmos-data:

https://github.com/HuayraLinux/huayra-ritmos-data/

**Comment by iglosiggio** [comment]
https://github.com/HuayraLinux/huayra-ritmos-extra/ está casi terminado :+1:
