### ISSUE TITLE
Modificar la funcionalidad del botón pintar

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#4]
Actualmente el botón pintar simplifica la selección de varios steps con solo mover el mouse, pero es un poco difícil manejar dado que queda pulsado, y el movimiento del mouse "invierte" la selección mientras se mueve.

Mi idea es quitar el botón limpiar, pero conservar su funcionalidad. Me parece más simple hacer que la acción de comenzar a pintar esté asociada al evento "drag" y dejar de pintar al evento "drop". De esa forma, podríamos permitirle a los usuarios marcar varias celdas manteniendo pulsado el botón del mouse y arrastrando.

Habría que modificar otra cosa más, al menos la observé en el FLStudio y me pareció muy buena idea, si se pulsa sobre un step vacío se asume que el usuario quiere "pintar" steps. Y si hace click sobre un step pintado vacío se asume que quiere "borrar" los steps. Así, cuando el usuario arrastra el mouse la acción sobre los steps es siempre la misma, o comienza a pintar o comienza a borrar steps. Actualmente la acción es invertir el estado del step actual...

**Comment by iglosiggio** [comment]
Esto lo reparé hace mil y no cerré :( 

El cambio está en 6620e8952ef91b723a184044ba6f994aa0f3d8fc cierro ^^
