### ISSUE TITLE
Falla el arranque de la aplicación si no está el archivo de configuración

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#42]
Al iniciar la aplicación queda completamente en blanco :(

![huayra ritmos 2016-09-01 11-18-22](https://cloud.githubusercontent.com/assets/99183/18170741/dbee6fec-7035-11e6-9f6a-07200682a749.png)

Debería crear el archivo de configuración si no lo encuentra o iniciar con parámetros por omisión.

**Comment by iglosiggio** [comment]
Fixeado en ef662aa47669bbe34da784e1add7c47d48d83dae
