### ISSUE TITLE
Revisar validador contra proyectos sin título

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#44]
Noté que la aplicación te permite crear proyectos sin nombre. Me imagino que tal vez alguna validación se está omitiendo, porque incluso se pueden crear varios proyectos sin nombre:

![huayra con debsign running 2016-09-09 14-05-52](https://cloud.githubusercontent.com/assets/99183/18395775/882cad8a-7696-11e6-8a62-da317ce62fa1.png)

Pienso que lo ideal sería que solo te permita crear nombres, y prohiba nombres nulos, o varios espacios o cosas raras como acá:

![huayra con debsign running 2016-09-09 14-07-20](https://cloud.githubusercontent.com/assets/99183/18395815/bd15d9b8-7696-11e6-81a4-10e12d0d2d23.png)

**Comment by iglosiggio** [comment]
Debería cerrarse con el commit, de todas formas necesita testing para ver que haya quedado todo bien (es probable que haya algún caso que no contemplé)

**Comment by hugoruscitti** [comment]
Creo que está perfecto @iglosiggio, le agregué unos tests para que nos aseguremos que siga andando en el futuro.
