### ISSUE TITLE
Generar formato de exportación e importación para los ritmos.

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#5]
Actualmente la aplicación puede guardar ritmos de manera interna, pero no permite exportarlos o guardar en archivo.

La idea es implementar las acciones de "exportar" e "importar" proyectos usando archivos; para esto habría que añadir las acciones a la aplicación y además crear un formato de archivo especial para la aplicación, donde se puedan guardar los "patterns" del proyecto y los samples utilizados.

Es un poco más complejo de lo que parece en principio, porque me parece que deberíamos guardar todos los samples junto con la data del proyecto y comprimir todo para que el formato sea un archivo autocontenido (no un directorio o un conjunto de archivos) similar a .zip o algo así.

Hay unas pruebas en la ruta "/playground" donde se pueden ver diálogos de exportación y generación de archivos .zip

**Comment by iglosiggio** [comment]
Con 0055f59732f4c8fa3ea2d6bb6796b401e459ce23 tenemos una implementación simple del sistema, cierro el issue temporalmente, ya que el formato tiene que más adelante avanzar para detectar y agregar los samples utilizados que no formen parte de una instalación de huayra-ritmos default.
