### ISSUE TITLE
Añadir dialogo de confirmación al eliminar un ritmo desde la pantalla inicial

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/huayra-ritmos#6]
Actualmente se pueden borrar ritmos desde la lista de proyectos, pero no se muestran ningún dialogo de confirmación.

La idea es mostrar alguna pregunta tipo "¿realmente quieres borrar este ritmo?, la operación no se podrá deshacer" o similar...

![huayra-ritmos 2015-07-22 10-11-21](https://cloud.githubusercontent.com/assets/99183/8826060/273f169e-305a-11e5-825c-f7fd62b753a2.png)

**Comment by iglosiggio** [comment]
Cierro este issue dada la opción de armar un botón de "deshacer" propuesta en #25. (Y porque #25 es más nuevo)
