### ISSUE TITLE
En el tamaño de ventana por defecto, no entra el diálogo de instrumentos.

### ISSUE THREAD

**Issue by digitalh** [hugoruscitti/huayra-ritmos#9]
El tamaño de ventana por defecto es chico y quedan afuera los botones de Guardar para elegir instrumento.
![huayra-ritmos_011](https://cloud.githubusercontent.com/assets/4365423/9065510/3aab990c-3aa8-11e5-9877-410e00acb92b.png)

**Comment by hugoruscitti** [comment]
![huayra-ritmos 2015-08-05 12-11-33](https://cloud.githubusercontent.com/assets/99183/9089445/85ceec5e-3b6b-11e5-9bd4-f02b7709e15e.png)
